"""
Minimal Transformer trained on modular Fibonacci sequences.

Reproduces and extends the grokking experiments from:
  Nanda et al. (2023) "Progress measures for grokking via mechanistic interpretability"
  https://arxiv.org/abs/2301.05217

Task: given a sequence governed by x_{t+1} = (x_t + x_{t-1}) mod p, predict the
next token autoregressively.  The model must discover that only the last two tokens
determine the next one, and ideally encode them via trigonometric functions at a
small set of key frequencies.

Dataset split guarantee
-----------------------
Training sequences are generated by extending randomly chosen seed pairs forward.
Every consecutive pair (x_i, x_{i+1}) appearing in any training sequence is
recorded in FibonacciTrainDataset.seen_pairs.  Validation sequences are then
constructed so that their terminal pair — (x[T-2], x[T-1]), the pair that
uniquely determines the next prediction — does not appear in seen_pairs.

For seq_len=2 (Nanda's setup) this is an exact pair-level split: every pair
appears in exactly one sequence, so seen_pairs = train seeds.  For seq_len > 2
intermediate pairs within a validation sequence may coincide with training pairs
(because the Fibonacci orbit chains pairs together), but the final prediction
task is always held out.
"""

import math
import random
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

import analysis as a

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class TrainConfig:
    """All hyperparameters in one place for easy experimentation."""
    p: int = 113                # prime modulus; Nanda et al. use 113
    vocab_size: int = p+1       # p + 1: tokens 0..p-1 plus "=" at index p
    d_model: int = 128
    n_heads: int = 4
    num_layers: int = 1
    hidden_mlp: int = 512
    seq_len: int = 3            # [a, b, =] — Nanda et al. format
    batch_size: int = 1000
    lr: float = 1e-3
    weight_decay: float = 1  # drives grokking (see diagnostic_metrics.tex §7); LR decay controls oscillations
    epochs: int = 15000
    train_frac: float = 0.3     # fraction of all p² pairs used for training
    monitor_every: int = 50     # epochs between spectral snapshots (0 = off)
    checkpoint_path: Optional[str] = None
    # Reproducibility: set data_seed=0 and torch_seed=0 to match Nanda et al.'s
    # default Config (seed=0 for pair-split; torch seed is not fixed in his code
    # but 0 is a clean baseline for comparison).
    data_seed: int = 0         # seed for the train/val pair split
    torch_seed: int = 0         # seed for model weight initialisation


# ---------------------------------------------------------------------------
# Utility: Fibonacci recurrence
# ---------------------------------------------------------------------------

def _fib_forward(seed: Tuple[int, int], length: int, mod: int) -> List[int]:
    """Return a Fibonacci sequence mod p of `length` starting from seed (a, b)."""
    seq = list(seed)
    while len(seq) < length:
        seq.append((seq[-1] + seq[-2]) % mod)
    return seq


def _fib_backward(terminal: Tuple[int, int], total_length: int, mod: int) -> List[int]:
    """
    Build a Fibonacci sequence of `total_length` whose last two elements are
    `terminal`.  Uses the backward recurrence x_{t-2} = x_t - x_{t-1} (mod p).
    """
    seq = list(terminal)
    while len(seq) < total_length:
        seq.insert(0, (seq[1] - seq[0]) % mod)
    return seq


# ---------------------------------------------------------------------------
# Datasets
# ---------------------------------------------------------------------------

def _make_pair_split(
    mod: int, train_frac: float = 0.8, seed: int = 42
) -> Tuple[List[Tuple[int, int]], List[Tuple[int, int]]]:
    """Randomly partition all mod² pairs into (train_seeds, val_seeds)."""
    all_pairs = [(a, b) for a in range(mod) for b in range(mod)]
    rng = random.Random(seed)
    rng.shuffle(all_pairs)
    n_train = int(train_frac * len(all_pairs))
    return all_pairs[:n_train], all_pairs[n_train:]


class FibonacciTrainDataset(Dataset):
    """
    Training dataset — Nanda et al. format: [a, b, =] → predict c at position 2.

    Each sample is (x, y) where:
      x = [a, b, eq]   — input sequence of length 3
      y = [b, eq, c]   — targets shifted one step right (c = (a+b) % mod)
    Loss is computed only at the last position (predicting c from [a, b, =]).

    Attributes
    ----------
    seen_pairs : set of (int, int)
        The (a, b) seed pairs used for training.  Passed to FibonacciValDataset
        to guarantee that validation pairs are held out.
    """

    def __init__(
        self,
        mod: int = 113,
        seq_len: int = 3,
        train_frac: float = 0.3,
        seed: int = 42,
    ) -> None:
        self.mod = mod
        self.seq_len = seq_len
        eq = mod                 # "=" token lives at index p

        train_seeds, self._val_seeds = _make_pair_split(mod, train_frac, seed)

        self.seen_pairs: Set[Tuple[int, int]] = set()
        self.samples: List[Tuple[torch.Tensor, torch.Tensor]] = []

        for (a, b) in train_seeds:
            c = (a + b) % mod
            x = torch.tensor([a, b, eq], dtype=torch.long)
            y = torch.tensor([b, eq, c], dtype=torch.long)
            self.seen_pairs.add((a, b))
            self.samples.append((x, y))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.samples[idx]


class FibonacciValDataset(Dataset):
    """
    Validation dataset — Nanda et al. format: [a, b, =] → predict c at position 2.

    Each validation pair (a, b) is guaranteed not to appear in the training set,
    so the corresponding prediction c = (a+b) % mod is strictly held out.

    Parameters
    ----------
    train_ds    : the FibonacciTrainDataset to test against
    num_samples : number of validation sequences to generate
    seed        : random seed
    """

    def __init__(
        self,
        train_ds: FibonacciTrainDataset,
        num_samples: int = 500,
        seed: int = 0,
    ) -> None:
        mod  = train_ds.mod
        eq   = mod               # "=" token lives at index p
        seen = train_ds.seen_pairs

        unseen = [
            (a, b) for a in range(mod) for b in range(mod)
            if (a, b) not in seen
        ]
        if not unseen:
            raise ValueError(
                "No unseen pairs available for validation. "
                "Lower train_frac."
            )

        rng = random.Random(seed)
        self.samples: List[Tuple[torch.Tensor, torch.Tensor]] = []

        for _ in range(num_samples):
            a, b = rng.choice(unseen)
            c = (a + b) % mod
            x = torch.tensor([a, b, eq], dtype=torch.long)
            y = torch.tensor([b, eq, c], dtype=torch.long)
            self.samples.append((x, y))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.samples[idx]


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class MLP(nn.Module):
    def __init__(self, d_model: int, hidden_dim: int) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d_model, hidden_dim),
            nn.ReLU(),
            #nn.Linear(hidden_dim, hidden_dim),
            #nn.ReLU(),
            nn.Linear(hidden_dim, d_model),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class MinimalTransformer(nn.Module):
    """
    Decoder-only transformer with causal self-attention, no layer norm.

    Follows the architecture in Nanda et al. (2023): token + positional
    embeddings fed into alternating attention and MLP residual blocks,
    projected to vocabulary logits.  Layer norm is omitted to keep the
    residual stream algebraically clean for mechanistic analysis.
    """

    def __init__(
        self,
        vocab_size: int,
        d_model: int = 128,
        n_heads: int = 4,
        num_layers: int = 1,
        max_seq_len: int = 20,
        hidden_mlp: int = 512,
    ) -> None:
        super().__init__()
        self.vocab_size = vocab_size
        self.d_model    = d_model
        self.token_embed = nn.Embedding(vocab_size, d_model)
        self.pos_embed   = nn.Embedding(max_seq_len, d_model)
        self.attn_layers = nn.ModuleList([
            nn.MultiheadAttention(d_model, n_heads, batch_first=True, dropout=0.0, bias=False)
            for _ in range(num_layers)
        ])
        self.mlp_layers = nn.ModuleList([
            MLP(d_model, hidden_mlp) for _ in range(num_layers)
        ])
        self.out_proj = nn.Linear(d_model, vocab_size)

        # Match Nanda's init: all weight matrices ~ N(0, 1/sqrt(d_model)), biases = 0
        std = 1.0 / math.sqrt(d_model)
        nn.init.normal_(self.token_embed.weight, std=std)
        nn.init.normal_(self.pos_embed.weight,   std=std)
        nn.init.normal_(self.out_proj.weight,    std=std)
        nn.init.zeros_(self.out_proj.bias)
        for attn in self.attn_layers:
            nn.init.normal_(attn.in_proj_weight, std=std)
            nn.init.normal_(attn.out_proj.weight, std=std)
        for mlp in self.mlp_layers:
            nn.init.normal_(mlp.net[0].weight, std=std)
            nn.init.zeros_(mlp.net[0].bias)
            nn.init.normal_(mlp.net[2].weight, std=std)
            nn.init.zeros_(mlp.net[2].bias)

    def forward(self, tokens: torch.Tensor) -> torch.Tensor:
        """tokens : LongTensor [B, T]  →  logits : FloatTensor [B, T, vocab_size]"""
        B, T = tokens.shape
        pos = torch.arange(T, device=tokens.device)
        x = self.token_embed(tokens) + self.pos_embed(pos).unsqueeze(0)
        causal_mask = torch.triu(
            torch.full((T, T), float("-inf"), device=tokens.device), diagonal=1
        )
        for attn, mlp in zip(self.attn_layers, self.mlp_layers):
            x = x + attn(x, x, x, attn_mask=causal_mask)[0]
            x = x + mlp(x)
        return self.out_proj(x)

    def token_embeddings(self) -> torch.Tensor:
        """W_E : FloatTensor [vocab_size, d_model] (detached)."""
        return self.token_embed.weight.detach()


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def _loss_and_acc(
    logits: torch.Tensor, targets: torch.Tensor
) -> Tuple[torch.Tensor, float]:
    """
    Cross-entropy loss and accuracy evaluated only at the last position.

    In the Nanda format [a, b, =] → [b, =, c], only position 2 (predicting c
    from context [a, b, =]) is used in the loss.  Positions 0 and 1 are
    skipped: they involve predicting b and "=" which carry no information about
    generalisation of the modular-addition rule.
    """
    logits_flat  = logits[:, -1, :]   # [B, vocab_size]
    targets_flat = targets[:, -1]     # [B]
    # Compute loss in float64: float32 log_softmax underflows on confident logits,
    # quantising gradients to multiples of ~1.2e-7 and producing dodgy gradient
    # estimates that cause limit-cycle oscillations (Nanda et al. use the same fix).
    logprobs = F.log_softmax(logits_flat.double(), dim=-1)
    loss = -logprobs.gather(1, targets_flat.unsqueeze(1)).squeeze(1).mean()
    acc  = (logits_flat.argmax(-1) == targets_flat).float().mean().item()
    return loss, acc


@torch.no_grad()
def evaluate(model: nn.Module, loader: DataLoader) -> Tuple[float, float]:
    """Return (mean_loss, mean_accuracy) over the full DataLoader."""
    model.eval()
    total_loss = total_acc = n = 0
    for x, y in loader:
        x, y = x.to(device), y.to(device)
        loss, acc = _loss_and_acc(model(x), y)
        total_loss += loss.item(); total_acc += acc; n += 1
    return total_loss / n, total_acc / n


def train_model(
    model: nn.Module,
    train_loader: DataLoader,
    val_loader: DataLoader,
    cfg: TrainConfig,
) -> Dict:
    """
    Train and return a history dict:
      "train_loss", "val_loss", "train_acc", "val_acc" — one value per epoch
      "spectral" — list of snapshot dicts (epoch, diag_mass, xi, peak),
                   populated every cfg.monitor_every epochs if > 0
    """
    optimizer = torch.optim.AdamW(
        model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay,
        betas=(0.9, 0.98),
    )
    scheduler = torch.optim.lr_scheduler.LambdaLR(
        optimizer, lr_lambda=lambda step: min(step / 10, 1.0)
    )
    history: Dict = {
        "train_loss": [], "val_loss": [],
        "train_acc":  [], "val_acc":  [],
        "spectral": [],
    }
    t0 = time.time()

    for epoch in range(cfg.epochs):
        model.train()
        ep_loss = ep_acc = n_batches = 0
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            loss, acc = _loss_and_acc(model(x), y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            scheduler.step()
            ep_loss += loss.item(); ep_acc += acc; n_batches += 1

        train_loss = ep_loss / n_batches
        train_acc  = ep_acc  / n_batches
        val_loss, val_acc = evaluate(model, val_loader)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        if cfg.monitor_every > 0 and epoch % cfg.monitor_every == 0:
            obs = a.monitor_spectral_observables(
                model=model, n=cfg.p, seq_len=cfg.seq_len,
                device=device, batch_size=cfg.batch_size,
                eq_token=cfg.p,
            )
            history["spectral"].append({
                "epoch":     epoch,
                "diag_mass": obs["diagonal_spectral_mass"],
                "xi":        obs["correlation_length"],
                "peak":      obs["peak_index"],
            })

        if (epoch + 1) % 100 == 0:
            print(
                f"Epoch {epoch + 1:5d}/{cfg.epochs}  "
                f"train loss {train_loss:.4f} acc {train_acc:.3f}  "
                f"val loss {val_loss:.4f} acc {val_acc:.3f}"
            )

    print(f"Training time: {time.time() - t0:.1f}s")
    return history


# ---------------------------------------------------------------------------
# Visualisation: loss / accuracy curves
# ---------------------------------------------------------------------------

def plot_training_curves(history: Dict, title: str = "") -> None:
    fig, (ax_loss, ax_acc) = plt.subplots(1, 2, figsize=(12, 4))
    epochs = range(1, len(history["train_loss"]) + 1)
    suffix = f" — {title}" if title else ""

    ax_loss.semilogy(epochs, history["train_loss"], label="train")
    ax_loss.semilogy(epochs, history["val_loss"],   label="val")
    ax_loss.set_xlabel("epoch"); ax_loss.set_ylabel("loss (log scale)")
    ax_loss.set_title(f"Loss{suffix}"); ax_loss.legend()

    ax_acc.plot(epochs, history["train_acc"], label="train")
    ax_acc.plot(epochs, history["val_acc"],   label="val")
    ax_acc.set_xlabel("epoch"); ax_acc.set_ylabel("accuracy")
    ax_acc.set_title(f"Accuracy{suffix}"); ax_acc.legend()

    plt.tight_layout(); plt.show()


# ---------------------------------------------------------------------------
# Visualisation: spectral monitoring over training
# ---------------------------------------------------------------------------

def plot_spectral_history(history: Dict) -> None:
    """Plot diagonal spectral mass and Ornstein–Zernike ξ from training history."""
    snaps = history.get("spectral", [])
    if not snaps:
        print("No spectral snapshots recorded (set monitor_every > 0).")
        return
    epochs = [s["epoch"]     for s in snaps]
    diag   = [s["diag_mass"] for s in snaps]
    xi     = [s["xi"]        for s in snaps]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    ax1.plot(epochs, diag, marker="o")
    ax1.set_xlabel("epoch"); ax1.set_ylabel("diagonal spectral mass M_diag")
    ax1.set_title("Diagonal spectral mass during training")

    ax2.plot(epochs, xi, marker="o", color="tab:orange")
    ax2.set_xlabel("epoch"); ax2.set_ylabel("correlation length ξ")
    ax2.set_title("Ornstein–Zernike correlation length")

    plt.tight_layout(); plt.show()


# ---------------------------------------------------------------------------
# Visualisation: trigonometric representation (Nanda et al., §3)
# ---------------------------------------------------------------------------

def embedding_fourier_amplitudes(W_E: torch.Tensor, p: int = None) -> np.ndarray:
    """
    Decompose token embeddings along the discrete Fourier basis and return the
    per-frequency amplitude.

    W_E : FloatTensor [vocab_size, d_model]
    p   : if given, only the first p rows are used (excludes the "=" token)
    amplitude : ndarray [p // 2 + 1]  — L2 norm over d_model for each frequency
    """
    if p is not None:
        W_E = W_E[:p]
    F = torch.fft.rfft(W_E, dim=0, norm="ortho")   # [p//2+1, d_model]
    return F.abs().pow(2).sum(dim=-1).sqrt().cpu().numpy()


def plot_embedding_fourier_spectrum(model: MinimalTransformer, p: int = None) -> None:
    """
    Bar chart of Fourier amplitudes of the token embedding matrix W_E.

    A grokked model concentrates power at a small number of key frequencies.
    Use this to identify which frequencies to pass to
    plot_embedding_trig_components.

    p : if given, only the first p token rows are analysed (excludes "=" token)
    """
    amp   = embedding_fourier_amplitudes(model.token_embeddings().cpu(), p=p)
    freqs = np.arange(len(amp))

    plt.figure(figsize=(10, 4))
    plt.bar(freqs, amp, width=0.8)
    plt.xlabel("frequency index k")
    plt.ylabel("‖F_k‖₂  (summed over d_model)")
    plt.title("Fourier spectrum of token embeddings W_E")
    plt.tight_layout(); plt.show()


def plot_embedding_trig_components(
    model: MinimalTransformer, freq: int, p: int = None
) -> None:
    """
    Scatter-plot token embeddings projected onto the cosine and sine basis
    vectors for a given frequency.

    Nanda et al. show that after grokking token k maps to a point near
    (cos(2πf·k/p), sin(2πf·k/p)) for each key frequency f, i.e., the
    tokens are evenly spaced on a circle.  This plot lets you verify that.

    Parameters
    ----------
    model : trained MinimalTransformer
    freq  : Fourier frequency index to inspect (use plot_embedding_fourier_spectrum
            to identify dominant ones; skip DC at index 0)
    p     : if given, only the first p rows of W_E are used (excludes "=" token)
    """
    W_E = model.token_embeddings().cpu().numpy()   # [vocab_size, d]
    if p is not None:
        W_E = W_E[:p]
    p   = W_E.shape[0]
    k   = np.arange(p)

    # Fourier basis vectors in token space (shape [p])
    cos_basis = np.cos(2 * np.pi * freq * k / p)
    sin_basis = np.sin(2 * np.pi * freq * k / p)

    # Project W_E along the token axis to get the corresponding directions
    # in d-dimensional embedding space (shape [d]).
    # If W_E[k] ≈ A·cos(2πfk/p)·u + A·sin(2πfk/p)·v, then
    # W_E.T @ cos_basis ∝ u and W_E.T @ sin_basis ∝ v.
    cos_dir = W_E.T @ cos_basis          # shape [d]
    sin_dir = W_E.T @ sin_basis          # shape [d]
    cos_dir /= np.linalg.norm(cos_dir) + 1e-8
    sin_dir /= np.linalg.norm(sin_dir) + 1e-8

    # Project each token's embedding onto these d-space directions (shape [p])
    cos_proj = W_E @ cos_dir
    sin_proj = W_E @ sin_dir

    fig, ax = plt.subplots(figsize=(5, 5))
    sc = ax.scatter(cos_proj, sin_proj, c=k, cmap="hsv", s=30, zorder=3)
    r  = np.hypot(cos_proj, sin_proj).mean()
    th = np.linspace(0, 2 * np.pi, 300)
    ax.plot(r * np.cos(th), r * np.sin(th), "k--", lw=0.8, alpha=0.4)

    plt.colorbar(sc, ax=ax, label="token index k")
    ax.set_aspect("equal")
    ax.set_xlabel(f"projection onto cos(2π·{freq}·k/p)")
    ax.set_ylabel(f"projection onto sin(2π·{freq}·k/p)")
    ax.set_title(f"Token embeddings — frequency {freq}")
    plt.tight_layout(); plt.show()


def plot_logit_structure_factor(model: MinimalTransformer, cfg: TrainConfig) -> None:
    """
    Compute and display the 2-D structure factor S(k, l) of the model's logit
    table at the current checkpoint.

    S(k, l) is the class-summed power spectrum on the pair-state lattice Z_p².
    After grokking the model learns the modular-addition rule and S concentrates
    on the diagonal k = l (see the phase-transition notes, §4–5).

    Shows two panels:
      Left  — log(1 + S(k, l)) as a heatmap (DC zeroed for visibility)
      Right — row-summed power vs diagonal power, with M_diag annotated
    """
    obs = a.monitor_spectral_observables(
        model=model, n=cfg.p, seq_len=cfg.seq_len,
        device=device, batch_size=cfg.batch_size,
        eq_token=cfg.p,
    )
    S = obs["structure_factor"].cpu().numpy()
    n = S.shape[0]

    S_display = S.copy()
    S_display[0, 0] = 0.0          # zero DC so colour scale is meaningful

    fig, (ax_map, ax_bar) = plt.subplots(1, 2, figsize=(13, 5))

    im = ax_map.imshow(
        np.log1p(S_display), origin="lower", cmap="inferno",
        extent=[0, n, 0, n],
    )
    ax_map.set_xlabel("ℓ (frequency in b-direction)")
    ax_map.set_ylabel("k (frequency in a-direction)")
    ax_map.set_title("log(1 + S(k, ℓ)) — full spectrum")
    plt.colorbar(im, ax=ax_map)

    idx = np.arange(n)
    ax_bar.plot(idx, S_display.sum(axis=1), label=r"row sum $\sum_ℓ S(k,ℓ)$")
    ax_bar.plot(idx, S_display[idx, idx],   label="diagonal S(k,k)")
    ax_bar.set_xlabel("k")
    ax_bar.set_ylabel("power")
    ax_bar.set_title(
        f"Diagonal spectral mass M_diag = {obs['diagonal_spectral_mass']:.3f}"
    )
    ax_bar.legend()

    plt.tight_layout(); plt.show()


def plot_trig_overview(model: MinimalTransformer, cfg: TrainConfig, top_k: int = 3) -> None:
    """
    Convenience wrapper: Fourier spectrum, structure factor heatmap, and
    trig-circle plots for the top-k dominant frequencies (DC excluded).
    """
    plot_logit_structure_factor(model, cfg)
    plot_embedding_fourier_spectrum(model, p=cfg.p)

    amp   = embedding_fourier_amplitudes(model.token_embeddings().cpu(), p=cfg.p)
    freqs = np.argsort(amp[1:])[::-1][:top_k] + 1   # skip DC at index 0
    for f in freqs:
        plot_embedding_trig_components(model, int(f), p=cfg.p)


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------

def save_checkpoint(model: nn.Module, history: Dict, path: str) -> None:
    torch.save({"model_state_dict": model.state_dict(), "history": history}, path)
    print(f"Checkpoint saved → {path}")


def load_checkpoint(model: nn.Module, path: str) -> Dict:
    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    return ckpt.get("history", {})


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    cfg = TrainConfig()

    torch.manual_seed(cfg.torch_seed)

    train_ds = FibonacciTrainDataset(
        mod=cfg.p, seq_len=cfg.seq_len, train_frac=cfg.train_frac,
        seed=cfg.data_seed,
    )
    val_ds = FibonacciValDataset(train_ds, num_samples=500)

    n_unseen = sum(
        1 for a in range(cfg.p) for b in range(cfg.p)
        if (a, b) not in train_ds.seen_pairs
    )

    cfg.batch_size = len(train_ds)   # full-batch: one gradient step per epoch

    print(
        f"p={cfg.p}  vocab_size={cfg.vocab_size}  seq_len={cfg.seq_len}\n"
        f"Train sequences : {len(train_ds)}\n"
        f"Val sequences   : {len(val_ds)}\n"
        f"Unseen pairs    : {n_unseen} / {cfg.p ** 2}"
    )

    train_loader = DataLoader(
        train_ds, batch_size=cfg.batch_size, shuffle=True,
        num_workers=4, pin_memory=True, persistent_workers=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=cfg.batch_size,
        num_workers=4, pin_memory=True, persistent_workers=True,
    )

    model = MinimalTransformer(
        vocab_size=cfg.vocab_size, d_model=cfg.d_model, n_heads=cfg.n_heads,
        num_layers=cfg.num_layers, max_seq_len=cfg.seq_len,
        hidden_mlp=cfg.hidden_mlp,
    ).to(device)

    try:
        history = train_model(model, train_loader, val_loader, cfg)
    except KeyboardInterrupt:
        history = {k: [] for k in ("train_loss", "val_loss", "train_acc", "val_acc", "spectral")}

    val_loss, val_acc     = evaluate(model, val_loader)
    train_loss, train_acc = evaluate(model, train_loader)
    print(f"\nFinal — train acc: {train_acc:.3f}  val acc: {val_acc:.3f}")

    plot_training_curves(history, title=f"p={cfg.p}, d={cfg.d_model}")
    plot_spectral_history(history)
    plot_trig_overview(model, cfg)

    if cfg.checkpoint_path:
        save_checkpoint(model, history, cfg.checkpoint_path)
